### ISSUE TITLE
`import whatever from 'punycode'` not matched?

### ISSUE THREAD

**Issue by wojtekmaj** [NullVoxPopuli/punycode-detector#3]
In the source code, you can find

```
    findPuny(`"import 'punycode'"`),
    findPuny(`'import "punycode"'`),
```

it seems like it's a side-effect free import of punycode, which is ultra rare and rather nonsensical. I believe this `import` should be replaced with `from` in this particular case?

**Comment by NullVoxPopuli** [comment]
doh! you are correct! thank you. Fixed in 1.0.4
